#!/usr/bin/env bash
set -euo pipefail

CHANNEL="${1:-8.0}"
INSTALL_DIR="${DOTNET_INSTALL_DIR:-/usr/local/dotnet}"
SCRIPT_PATH="/tmp/dotnet-install.sh"
DOTNET_SDK_PACKAGE="${DOTNET_SDK_PACKAGE:-dotnet-sdk-8.0}"
MIRROR_SCRIPT_URL="${DOTNET_INSTALL_SCRIPT_URL:-}"
MIRROR_SDK_TARBALL_URL="${DOTNET_SDK_TARBALL_URL:-}"
MIRROR_SDK_SHA512="${DOTNET_SDK_SHA512:-}"
APT_MIRROR="${DOTNET_APT_MIRROR:-}"

log() { echo "[dotnet-install] $*"; }
warn() { echo "[dotnet-install][warn] $*"; }

have_cmd() { command -v "$1" >/dev/null 2>&1; }

export DOTNET_ROOT="$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"

try_cmd() {
  local description="$1"
  shift
  log "Trying: ${description}"
  if "$@"; then
    log "Success: ${description}"
    return 0
  fi
  log "Failed: ${description}"
  return 1
}

verify_dotnet() {
  if have_cmd dotnet; then
    dotnet --info >/dev/null 2>&1 && return 0 || return 1
  fi
  if [[ -x "$INSTALL_DIR/dotnet" ]]; then
    "$INSTALL_DIR/dotnet" --info >/dev/null 2>&1 && return 0 || return 1
  fi
  return 1
}

download_file() {
  local url="$1"
  local out="$2"
  if have_cmd curl; then
    curl -fsSL "$url" -o "$out"
  elif have_cmd wget; then
    wget -qO "$out" "$url"
  else
    warn "Neither curl nor wget is available"
    return 1
  fi
}

run_install_script() {
  local script_url="$1"
  if [[ -z "$script_url" ]]; then
    return 1
  fi

  if ! try_cmd "download installer script from ${script_url}" download_file "$script_url" "$SCRIPT_PATH"; then
    return 1
  fi

  chmod +x "$SCRIPT_PATH"
  try_cmd "run downloaded installer script" bash "$SCRIPT_PATH" --channel "$CHANNEL" --install-dir "$INSTALL_DIR" || return 1
  return 0
}

install_from_tarball_url() {
  local url="$1"
  local archive="/tmp/dotnet-sdk.tar.gz"

  if [[ -z "$url" ]]; then
    return 1
  fi

  if ! try_cmd "download SDK tarball from ${url}" download_file "$url" "$archive"; then
    return 1
  fi

  if [[ -n "$MIRROR_SDK_SHA512" ]]; then
    if ! have_cmd sha512sum; then
      warn "sha512sum not available; cannot verify DOTNET_SDK_SHA512"
      return 1
    fi
    echo "${MIRROR_SDK_SHA512}  ${archive}" > /tmp/dotnet-sdk.sha512
    try_cmd "verify SDK tarball SHA-512" sha512sum -c /tmp/dotnet-sdk.sha512 || return 1
  fi

  try_cmd "extract downloaded SDK tarball" tar -xzf "$archive" -C "$INSTALL_DIR" || return 1
  return 0
}

configure_apt_mirror() {
  local mirror="$1"
  local codename

  if [[ -z "$mirror" ]] || ! have_cmd apt-get; then
    return 1
  fi

  codename="$(. /etc/os-release && echo "${VERSION_CODENAME:-noble}")"
  log "Configuring apt mirror: ${mirror} (${codename})"

  cat > /etc/apt/sources.list <<APT
# Generated by install-dotnet.sh
# Mirror: ${mirror}
deb ${mirror} ${codename} main restricted universe multiverse
deb ${mirror} ${codename}-updates main restricted universe multiverse
deb ${mirror} ${codename}-backports main restricted universe multiverse
deb ${mirror} ${codename}-security main restricted universe multiverse
APT
}

if verify_dotnet; then
  log "dotnet already installed"
  dotnet --info || "$INSTALL_DIR/dotnet" --info
  exit 0
fi

mkdir -p "$INSTALL_DIR"

# Strategy 0: corporate/internal mirror overrides (if provided).
if [[ -n "$APT_MIRROR" ]]; then
  try_cmd "configure apt mirror" configure_apt_mirror "$APT_MIRROR" || true
fi

if [[ -n "$MIRROR_SCRIPT_URL" ]]; then
  try_cmd "install via custom installer URL" run_install_script "$MIRROR_SCRIPT_URL" || true
  if verify_dotnet; then
    log "dotnet installed via custom installer URL"
    "$INSTALL_DIR/dotnet" --info
    exit 0
  fi
fi

if [[ -n "$MIRROR_SDK_TARBALL_URL" ]]; then
  try_cmd "install via custom SDK tarball URL" install_from_tarball_url "$MIRROR_SDK_TARBALL_URL" || true
  if verify_dotnet; then
    log "dotnet installed via custom SDK tarball URL"
    "$INSTALL_DIR/dotnet" --info
    exit 0
  fi
fi

# Strategy 1: apt packages (if repositories are reachable).
if have_cmd apt-get; then
  try_cmd "apt-get update" apt-get update || true
  try_cmd "apt-get install ${DOTNET_SDK_PACKAGE}" apt-get install -y "$DOTNET_SDK_PACKAGE" || true
  if verify_dotnet; then
    log "dotnet installed via apt"
    dotnet --info || "$INSTALL_DIR/dotnet" --info
    exit 0
  fi
fi

# Strategy 2: Microsoft install script via curl/wget using existing proxy env.
try_cmd "run official installer script via default network path" run_install_script "https://dot.net/v1/dotnet-install.sh" || true
if verify_dotnet; then
  log "dotnet installed via official install script"
  "$INSTALL_DIR/dotnet" --info
  exit 0
fi

# Strategy 3: retry without proxy env (some environments only allow direct).
if have_cmd curl; then
  try_cmd "download install script with curl (no proxy)" env HTTPS_PROXY= HTTP_PROXY= ALL_PROXY= https_proxy= http_proxy= all_proxy= curl -fsSL https://dot.net/v1/dotnet-install.sh -o "$SCRIPT_PATH" || true
fi
if [[ -s "$SCRIPT_PATH" ]]; then
  chmod +x "$SCRIPT_PATH"
  try_cmd "run dotnet-install.sh without proxy env" env HTTPS_PROXY= HTTP_PROXY= ALL_PROXY= https_proxy= http_proxy= all_proxy= bash "$SCRIPT_PATH" --channel "$CHANNEL" --install-dir "$INSTALL_DIR" || true
  if verify_dotnet; then
    log "dotnet installed via dotnet-install.sh (no proxy)"
    "$INSTALL_DIR/dotnet" --info
    exit 0
  fi
fi

# Strategy 4: local offline archives if present.
for archive in \
  "/workspace/dotnet-sdk-${CHANNEL}-linux-x64.tar.gz" \
  "/workspace/dotnet-sdk-linux-x64.tar.gz" \
  "./dotnet-sdk-${CHANNEL}-linux-x64.tar.gz" \
  "./dotnet-sdk-linux-x64.tar.gz"; do
  if [[ -f "$archive" ]]; then
    log "Trying local archive: $archive"
    tar -xzf "$archive" -C "$INSTALL_DIR"
    if verify_dotnet; then
      log "dotnet installed from local archive"
      "$INSTALL_DIR/dotnet" --info
      exit 0
    fi
  fi
done

# Strategy 5: mise/asdf if available.
if have_cmd mise; then
  try_cmd "mise install dotnet@${CHANNEL}" mise install "dotnet@${CHANNEL}" || true
  if verify_dotnet; then
    log "dotnet installed via mise"
    dotnet --info || "$INSTALL_DIR/dotnet" --info
    exit 0
  fi
fi

log "Unable to install dotnet after all strategies."
log "If this environment is network-restricted, set internal mirror env vars (DOTNET_APT_MIRROR, DOTNET_INSTALL_SCRIPT_URL, DOTNET_SDK_TARBALL_URL) or provide a local SDK tarball and rerun this script."
exit 1
